on:
  workflow_dispatch: # Manual trigger to run a workflow
  schedule:
    - cron:  '0 * * * *' # Every hour
name: Daily Figures Update
jobs:
  create-and-push-figures:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Python scripts
      run: |
        python main.py
    - name: Commit figures
      run: |
        bash .github/workflows/commit.sh
    - name: Push new figures
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
