on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
name: Hourly weather update
jobs:
  create-and-push-figures:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Python scripts
      run: |
        python main.py
